### ISSUE TITLE
Discuss about using click for argument parsing

### ISSUE THREAD

**Issue by jorgepiloto** [jorsanpe/cpm#274]
Hi folks! 👋🏽

I just came across this amazing tool and found that you are using a custom argument parser, which is implemented in [argument_parser.py](https://github.com/jorsanpe/cpm/blob/master/cpm/argument_parser.py) and makes use of the `argparse`.

Have you considered to use [click](https://click.palletsprojects.com/en/8.0.x/) to achieve the same task? It would simplify the code quite a bit while providing the same functionalities.

If you want, I could work on this and open a pull request in case you are interested on this feature.

Thank you for this project, `cpm` is the tool I was looking for! 🖤

**Comment by jorsanpe** [comment]
Hi Jorge!

Thanks for your interest in the project.

One of the design principles I want to follow in cpm is to minimize the amount of dependencies the project has, that's why I went for `argparse`. 

Having said that, I agree that the current implementation of the argument parser is a bit of a mess 😅 . I wasn't aware of click, but it looks great. By all means, please, give it a try.

Regards

**Comment by jorgepiloto** [comment]
It is reasonable to lower the amount of dependencies within a project. Thanks for your response @jorsanpe. Closing this then 👍🏽
